n = 16
(
    GET_LANG,
    GET_NAME,
    GET_CONTACT,
    GET_PLATE_NUMBER,
    CLICK_LANG,
    ALL_SETTINGS,
    LANG_SETTINGS,
    NAME_SETTINGS,
    PHONE_SETTINGS,
    CHANGE_LANG,
    CHANGE_NAME,
    CHANGE_PHONE,
    CHANGE_PLATE_NUMBER,
    GET_SUGGESTION,
    COMMON_QUESTIONS,
    SELECT_STATION
) = range(0, n) 